// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwqocatsqqsiwwawnpts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3cW9jYXRzcXFzaXd3YXducHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzE1MDksImV4cCI6MjA2NzA0NzUwOX0.zr1LvfgXRqkIaAf45OiuZnSQoVQqOQdknAlGprPH78A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});